mysql:
    image: mysql:5.7
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} 
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
        - mysqldata:/var/lib/mysql
    ports:
        - ${HOST_MYSQL_PORT}:1234

        


